### PR TITLE
Solve Issues #16

### PR DESCRIPTION
**Pull request by AliLozano**
Solves #16 adding a file `.fontello-session`

### CODE REVIEW

**Comment by ryantsangai** [comment]
Waiting for PR long time, will it be merged? 
or this repo is no longer maintained?

**Comment by ryantsangai** [comment]
I've forked and merged this PR, work like a charm.
Thanks a lot

**Comment by paulyoung** [comment]
Sorry for the delay on this.

Are either of you interested in being a maintainer?

**Comment by AliLozano** [comment]
Are u using internet explorer? 3 years later!!!. No problem for me.

**Comment by syffs** [comment]
@paulyoung any reason why this cannot be merged ? along with #43

**Comment by paulyoung** [comment]
I added @AliLozano and @dlackty as collaborators a while back since I no longer use this so will defer to them.

**Comment by dlackty** [comment]
Hey all, I'll review this and get it merged in the following days.

**Pull request merged**
