### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by kayvanbree**
This should fix the invulnerabilites of fstream and unzip. Unzip is not maintained anymore, so I added the drop-in replacement unzip. However, this repo doesn't seem to be maintained either, so I hope @paulyoung will see this!

#34

### CODE REVIEW

**Comment by paulyoung** [comment]
Thanks @kayvanbree!

Are you using this package? Would you like to be added as a maintainer?

**Comment by kayvanbree** [comment]
Hey @paulyoung, I started using this package this week, because FontCustom is pretty unmaintained and there is a bug on Chrome/iOS that is probably not going to be fixed. 

It would be awesome if you added me as maintainer! Is there anything I should know when I become a maintainer?

**Comment by paulyoung** [comment]
@kayvanbree I don't use this package anymore or have time to maintain it, so I think it would make more sense for someone like yourself to manage issues and pull requests, make releases, publish to npm, etc

What do you think?

**Comment by azizur** [comment]
Hi @paulyoung and @kayvanbree Do we know when this will be released?

I use the package and would like to see a release to fix the current warnings fixed by this PR.

**Pull request merged**
